### ISSUE TITLE
Episode 2 Compatibility

### ISSUE THREAD

**Issue by yayvery** [ladosha/lis2-save-editor#1]
Loading an episode 2 save fails with this error:

![capture](https://user-images.githubusercontent.com/12583921/51933343-17711480-23cf-11e9-9ffb-a34d9e8d8ca8.PNG)

**Comment by ladosha** [comment]
I am still working on adding Episode 2 compatibility, hope to release it in a few days.

**Comment by ladosha** [comment]
Added Episode 2 support in [version 2.4](https://github.com/ladosha/lis2-save-editor/releases/tag/v2.4)
