### ISSUE TITLE
Support for remaining episodes possible

### ISSUE THREAD

**Issue by faxx1080** [ladosha/lis2-save-editor#3]
By using the QuickBMS script [here](https://zenhax.com/viewtopic.php?t=1005&start=1460) it is possible to extract the uncompressed save file for the full game, then modify the byte at offset 0x8 to be 0x02, and the editor works (barring the DateTime crash, which can be averted by adding a trycatch in the reader to substitute a valid date if an invalid date is read).

The game seems to read these uncompressed saves fine.

**Comment by IgelRM** [comment]
Great, thanks to spiritovod and you.

So for a quick workaround, the header detection needs to be updated from 0x02 to 0x03?
https://github.com/ladosha/lis2-save-editor/blob/master/lis2-save-editor/GameSave.cs#L32

How does your DateTime trycatch look like, can you create a PR?

**Comment by IgelRM** [comment]
Neat, export to JSON works. No FactNameForDebug yet unfortunately as they appear to have been added manually.

Checking the F_PROM_CashInInventory GUID (c68a73d0-7181-4924-994a-2833a01adc09) and it appears to be working, though I haven't tested thoroughly.

F_PROM_GEN_BRTHD: 0b7638e6-e4e4-4144-9a9f-2312082a9a12
F_PROM_GEN_MLTY: 317bd07c-6148-466e-9292-f805cb51cdc2

**Comment by faxx1080** [comment]
I was able to use that PR above to figure enough of the file format (and a lucky guess) on searching for the Sacrifice Arcadia Bay choice BooleanFact  GUID in the save file with a hex editor, to change a value of 0 to a 1 so I can re-play through forking from a completed file so I keep the "I've seen this cutscene" flags, but redo the game and see the results of that.
